# Generated by Django 5.1.6 on 2025-04-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='aadhar',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pan',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
